name: chowdown-importer

services:
  chowdown-importer:
    build: .
    container_name: chowdown-importer
    ports:
      - "8008:8000"
    env_file: .env
    volumes:
      - ./app:/app/app:ro
      - repo-data:/app/repo
    restart: unless-stopped

volumes:
  repo-data:
